service: ghost-publisher

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'us-east-1'}
  timeout: 120 # 2 minutes timeout
  memorySize: 512 # Increase memory for better performance
  environment:
    NODE_ENV: ${opt:stage, 'prod'}
    GHOST_URL: ${env:GHOST_URL, ''}
    GHOST_API_KEY: ${env:GHOST_API_KEY, ''}
    GHOST_NEWSLETTER_ID: ${env:GHOST_NEWSLETTER_ID, ''}

functions:
  ghostPublisher:
    handler: index.handler
    name: GhostPublisherFunction
    description: Publishes articles to Ghost CMS with improved error handling and retry logic
    timeout: 120 # 2 minutes timeout
    memorySize: 512
    events:
      - http:
          path: publish
          method: post
          cors: true

package:
  exclude:
    - node_modules/**
    - .git/**
    - .gitignore
    - README.md
    - test.js
    - .env
  include:
    - index.js
    - package.json
    - src/**
