AWSTemplateFormatVersion: '2010-09-09'
Description: 'Update Lambda function timeout to 5 minutes'

Parameters:
  FunctionName:
    Type: String
    Description: Name of the Lambda function to update
    Default: perplexity-geopolitical-risks-lambda

Resources:
  UpdateLambdaTimeout:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionName
      Timeout: 300  # 5 minutes in seconds

Outputs:
  UpdatedTimeout:
    Description: The updated timeout value for the Lambda function
    Value: 300
